### ISSUE TITLE
SEO optimization

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#16]
- [x] add meta tags
- [x] add aria labels on buttons, links, images, and other elements
- [x] use svg and webp image format for better render

**Comment by keerthanak-tw** [comment]
Can i work on this?

**Comment by 1stdevfriend** [comment]
Sure @keerthanak-tw

**Comment by 1stdevfriend** [comment]
Added you as an assignee :)

**Comment by keerthanak-tw** [comment]
Will it be possible for you to provide the descriptions to be added in meta for the pages? 
or can i go ahead and add one liners about the pages?

**Comment by 1stdevfriend** [comment]
Sure.

**Comment by keerthanak-tw** [comment]
Raised a PR for the second task. Kindly suggest if any more enhancement are required with respect to this task

**Comment by keerthanak-tw** [comment]
Raised PRs for all the tasks. Kindly review and merge if it looks good (expecting conflicts from other PRs. Hence, would be great if it can be fixed this week).

For the suggestion mentioned in #36 - if decided to have migration to other framework, it could be taken up as a separate issue as that task is not a small one. For now, this issue can be considered as done 🙂

**Comment by keerthanak-tw** [comment]
Hello...could you please check the merged PRs. I think two of them are missing hacktoberfest-accepted labels 😁 🙈
