### ISSUE TITLE
Footer section issues

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#20]
- [ ] Change the footer style right now all links are in a single column split into two column
- [ ] Add animation on hover on footer social links
- [ ] Add map links to the company address
- [ ] Look into it when clicking on any footer link and navigating to the page the page does not start from the top

**Comment by artimanputra** [comment]
Hey, I would like to work on this issue.

**Comment by 1stdevfriend** [comment]
Sure :)

**Comment by artimanputra** [comment]
> Sure :)

Can you please assign it to me?

**Comment by 1stdevfriend** [comment]
Done!

**Comment by 1stdevfriend** [comment]
@artimanputra

**Comment by 1stdevfriend** [comment]
Removing assignee. Feel free to pick it up.

**Comment by valasubramanian-tw** [comment]
@1stdevfriend I would like to work on this issue. Can you assign it to me?

**Comment by 1stdevfriend** [comment]
Sure. @valasubramanian-tw

**Comment by valasubramanian-tw** [comment]
@1stdevfriend On item #3 'Add map links to the company address', do you want to add another link 'Address' to the footer like below?

<img width="890" alt="Screenshot 2022-10-17 at 4 56 21 PM" src="https://user-
images.githubusercontent.com/110656887/196165745-71cbf6bc-cf2a-4627-90aa-a8e0d9d4f6f5.png">

And when you click on the link, do you want to display the contact us form as a page like below?

<img width="1314" alt="Screenshot 2022-10-17 at 4 55 27 PM" src="https://user-images.githubusercontent.com/110656887/196167670-6ad45edc-49f6-49a9-a70c-f52e686eeae1.png">

**Comment by valasubramanian-tw** [comment]
@1stdevfriend @abhirock1998  On item 3 'Add map links to the company address', do you want to add another link 'Address' to the footer like below?

<img width="890" alt="Screenshot 2022-10-17 at 4 56 21 PM" src="https://user-images.githubusercontent.com/110656887/196168281-823ab137-3392-45b8-b3a8-d380e6bc2ff6.png">


And when you click on the link, do you want to display the contact us form as a page like below?

<img width="1314" alt="Screenshot 2022-10-17 at 4 55 27 PM" src="https://user-images.githubusercontent.com/110656887/196168314-bc01879a-3646-4f99-b22f-12c830168bc8.png">

**Comment by 1stdevfriend** [comment]
No address won't be necessary. I believe we can remove that from the footer. @valasubramanian-tw

**Comment by valasubramanian-tw** [comment]
@1stdevfriend Created a PR for the first item. I will be raised separate PRs for other items in the list.
