### ISSUE TITLE
Home pages issues

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#21]
- [ ] Fix the home page about coders card width right now it looks like it's compressed
- [ ] Fix home page hero section company logo for large resolution devices
- [ ] Change Koders logo to new one use from the portfolio site
- [ ] Font family for How we work section in the home screen

**Comment by 201B153** [comment]
I will be working on it.

**Comment by 1stdevfriend** [comment]
Great! Add you as assignee

**Comment by 201B153** [comment]
> * [x]  Fix the home page about coders card width right now it looks like it's compressed
> * [ ]  Fix home page hero section company logo for large resolution devices
> * [x]  Change Koders logo to new one use from the portfolio site
> * [ ]  Font family for How we work section in the home screen

I will we working in stages.. currently completed.
- 
![image](https://user-images.githubusercontent.com/89572392/193899273-9f44a950-aec9-4a29-be28-0e21787819f0.png)
- Brief abt second part please I don't think it a issue at all it works fine.
- 
![image](https://user-images.githubusercontent.com/89572392/193903313-3c324ba4-728e-46ab-8e39-55d9171e676e.png)
- I don't see any issue with font here they all same over the page

@1stdevfriend review it and tell what to add or modify further.

**Comment by 201B153** [comment]
@1stdevfriend review It and let me know if there is anything to add or modify further.

**Comment by 1stdevfriend** [comment]
Looks good. @BasuDevTyagi10 can you close this and accept PR over dev branch?

**Comment by BasuDevTyagi10** [comment]
on it @1stdevfriend
