### ISSUE TITLE
Pages section responsiveness issue

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#22]
- [ ] Fix the home page about Koder's card width right now it looks like it's compressed
- [ ] Fix home page hero section company logo for large resolution devices
- [ ] Fix all pages Hero section
- [ ] update the discord embed in the community section
- [ ] Change the team section image width and height right now it is too big to try to use SVG and webp everywhere if possible
- [ ] Out project card, image width and height need to fix
- [ ] Update the portfolio section

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by 1stdevfriend** [comment]
Okay sure :)

**Comment by 1stdevfriend** [comment]
@semi-infiknight
